version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "8000:8000"
    depends_on:
      - service2

  service2:
    build: ./service2
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
